blueprint:
  description: Rookmelding - dan lamp fel wit aan 
  name: Lamp wit bij rook
  domain: automation
  author: Digital Domo
  
  input:
    target_light:
      name: Verlichting
      description: De verlichting die fel wit moet worden
      selector:
        target:
          entity:
            - domain: light
    smoke_detector:
      name: Rookmelders
      description: De rookmelder die rook heeft gedetecteerd
      selector:
        entity:
          filter:
            - domain: binary_sensor
              device_class: smoke
          multiple: false
    overrule_switches:
      name: Overbrugging
      description: Overbrugging zorgt ervoor dat overige automatiseringen niets conflicteren
      selector:
        entity: 
          filter:
            - domain: input_boolean
          multiple: true

triggers:
  - trigger: state
    entity_id: !input smoke_detector
    to:
      - "on"
    id: rook
  - trigger: state
    entity_id: !input smoke_detector
    to:
      - "off"
    id: geen rook
    for:
      hours: 0
      minutes: 2
      seconds: 0

actions:
  - choose:
      - conditions:
          - condition: trigger
            id:
              - rook
        sequence:
          - action: light.turn_on
            target: !input target_light
          - delay:
              hours: 0
              minutes: 0
              seconds: 2
              milliseconds: 0
          - action: light.turn_on
            target: !input target_light
            data:
              rgb_color:
                - 255
                - 255
                - 255
              brightness_pct: 100
          - action: input_boolean.turn_on
            target:
              entity_id: !input overrule_switches
      - conditions:
          - condition: trigger
            id:
              - geen rook
        sequence:
          - action: light.turn_on
            target: !input target_light
          - delay:
              hours: 0
              minutes: 0
              seconds: 2
              milliseconds: 0
          - action: light.turn_on
            target: !input target_light
            data:
              rgb_color:
                - 255
                - 255
                - 0
              brightness_pct: 31
          - delay:
              hours: 0
              minutes: 0
              seconds: 2
              milliseconds: 0
          - action: light.turn_off
            target: !input target_light
          - action: input_boolean.turn_off
            target:
              entity_id: !input overrule_switches

mode: single
