blueprint:
  description: Alarm - dan lamp rood aan 
  name: Lamp rood bij alarm
  domain: automation
  author: Digital Domo
  
  input:
    target_light:
      name: Verlichting
      description: De verlichting die rood moet worden (kan ook een ruimte zijn)
      selector:
        target:
          entity:
            - domain: light
    alarm_detector:
      name: Alarm sensoren
      description: De raam en/of deur sensoren die alarm detecteren
      selector:
        entity:
          filter:
            - domain: binary_sensor
              device_class: door
            - domain: binary_sensor
              device_class: window
          multiple: true
    overrule_switches:
      name: Overbrugging
      description: Overbrugging zorgt ervoor dat overige automatiseringen niets conflicteren
      selector:
        entity: 
          filter:
            - domain: input_boolean
          multiple: true

triggers:
  - trigger: state
    entity_id: !input alarm_detector
    to:
      - "on"
    id: alarm
  - trigger: state
    entity_id: !input alarm_detector
    to:
      - "off"
    id: geen alarm
    for:
      hours: 0
      minutes: 2
      seconds: 0

actions:
  - choose:
      - conditions:
          - condition: trigger
            id:
              - alarm
        sequence:
          - action: light.turn_on
            target: !input target_light
          - delay:
              hours: 0
              minutes: 0
              seconds: 2
              milliseconds: 0
          - action: light.turn_on
            target: !input target_light
            data:
              rgb_color:
                - 255
                - 255
                - 255
              brightness_pct: 100
          - action: input_boolean.turn_on
            target:
              entity_id: !input overrule_switches
      - conditions:
          - condition: trigger
            id:
              - geen alarm
        sequence:
          - action: light.turn_on
            target: !input target_light
          - delay:
              hours: 0
              minutes: 0
              seconds: 2
              milliseconds: 0
          - action: light.turn_on
            target: !input target_light
            data:
              rgb_color:
                - 255
                - 255
                - 0
              brightness_pct: 31
          - delay:
              hours: 0
              minutes: 0
              seconds: 2
              milliseconds: 0
          - action: light.turn_off
            target: !input target_light
          - action: input_boolean.turn_off
            target:
              entity_id: !input overrule_switches

mode: single
