blueprint:
  name: Motion Light Tutorial
  description: Turn a light on based on detected motion
  domain: automation
  author: Digital Domo
  input:
    motion_sensor:
      selector:
        entity:
          filter:
            - device_class: motion
              domain: binary_sensor
            - device_class: occupancy
              domain: binary_sensor
    target_light:
      selector:
        target:
          entity:
            - domain: light

triggers:
  - trigger: state
    entity_id: !input motion_sensor

actions:
  - action: >
      {% if trigger.to_state.state == "on" %}
        light.turn_on
      {% else %}
        light.turn_off
      {% endif %}
    target: !input target_light
