blueprint:
  name: Play Slow-Whoop on Google Speakers
  author: Digital Domo
  description: >
    📣 Dit script speelt een mp3 file genaamd slow-whoop.mp3 op Google Smart Speakers. Het bestand staat in een lokale /media directory.
  source_url: https://gitlab.com/digital-domo/ha-blueprints/raw/main/play_slow_whoop_on_google_speakers_script.yaml
  homeassistant:
    min_version: 2023.8.0
  domain: script
  input:
    volume:
      name: Het volume waarop afgespeeld wordt
      default: 0.3
      selector:
        number:
          min: 0.1
          max: 1
          step: 0.1
          mode: slider
    speaker_target:
      name: De Google speaker waar het geluid naar toe moet worden gestuurd
      selector:
        entity:
          multiple: true
          filter:
            - domain: media_player
    file_2_play:
      name: Media bestand dat afgespeeld wordt
      description: >
        Bijvoorbeeld: '/media/music/slow-whoop.mp3'.
        Hier vind je meer informatie: 
          (https://www.home-assistant.io/more-info/local-media/add-media/)
          (https://www.home-assistant.io/more-info/local-media/setup-media/)
          (https://www.home-assistant.io/integrations/media_source/)
      default: "/media/music/slow-whoop.mp3"
      selector:
        text:
    media_type:
      name: Media_Content_type
      description: >
        Informatie over Media Content Types: 
          (https://www.home-assistant.io/integrations/cast/)
          (https://developers.google.com/cast/docs/media/)
      default: "audio/mp3"
      selector:
        text:
    
sequence:
# - alias: Set het volume op de speaker
#   action: media_player.volume_set
#   data:
#     volume_level: !input volume
#     target:
#       entity_id: !input speaker_target

- alias: Speel mp3 op speaker
  action: media_player.play_media
  data:
    entity_id: !input speaker_target
    media_content_id: !input file_2_play
    media_content_type: !input media_type

#mode: queued
icon: mdi:music-clef-bass
#max: 2