---
blueprint:
  name: Batterij vervangen
  description: Zet de huidige datum als vervangdatum voor een batterij sensor
  domain: automation

  input:
    motion_sensor:
       selector:
         entity:
           filter:
             - device_class: motion
               domain: binary_sensor
             - device_class: occupancy
               domain: binary_sensor

actions:
  - action: battery_notes.set_battery_replaced
    data: 
      device_id: !input motion_sensor
