blueprint:
  name: Presence Light Off
  description: Doe het licht uit als niemand meer thuis is
  domain: automation
  author: Digital Domo
  input:
    target_light:
      selector:
        target:
          entity:
            - domain: light

triggers:
  - trigger: numeric_state
    entity_id:
      - zone.home
    below: 1

actions:
  - action: light.turn_off
    target: !input target_light

mode: single
