blueprint:
  name: Presence Light Off
  description: Doe het licht uit als niemand meer thuis is
  domain: automation
  author: Digital Domo

  input:
    target_light:
      name: Verlichting
      description: Kies de verlichting die aangeschakeld moet gaan worden
      selector:
        target:
          entity:
            - domain: light
    home_zone:
      name: Home Zone
      description: De zone die gebruikt wordt voor de thuislocatie
      selector:
        entity:
          filter:
            - domain: zone

triggers:
  - trigger: numeric_state
    entity_id: !input home_zone
    below: 1

actions:
  - action: light.turn_off
    target: !input target_light

mode: single
