blueprint:
  description: >
    Zet de status van een binairy_sensor entity op "off" wanneer deze te lang op "on" blijft staan.
    De service in deze automatisering maakt gebruik van een python script.


     💡 De voorwaarden voor deze automatisering zijn daarom het volgende:
    - deze directory moet aanwezig zijn in Home Asistant: **/config/python_scripts**
    - in die directory moet het bestand **set_state.py** aanwezig zijn
    

    Het bestand set_state.py staat ook in deze repository, kopieer de RAW versie en plak die in /config/puthon_scripts/set_state.py

  name: Wijzig de status van een binary_sensor entiteit van "on" naar "off"
  domain: automation
  author: Digital Domo
  
  input:
    entiteit:
      name: entiteit
      description: De binary_sensor waarvan de staus gewijzigd moet worden
      selector:
        target:
          entity:
            - domain: binary_sensor

    # status:
    #   name: status
    #   description: De nieuwe status van de binary_sensor
    #   selector:
    #     select:
    #       options:
    #         - "on"
    #         - "off"

    tijd:
      name: tijd
      description: De tijd in minuten dat de status van de binary_entity op "on" is blijven staan (default=5)
      selector:
        number:
          min: 1
          max: 60
          step: 1
          unit_of_measurement: minutes
          mode: slider
      default: 5

triggers:
  - trigger: state
    entity_id: !input entiteit
    to:
      - "on"
    for:
      hours: 0
      minutes: !input tijd
      seconds: 0

actions:
  - action: pyhon_script.set_state
    data:
      entity_id: !input entiteit
      state: "on"
